name: lss
version: 0.1.1
summary: Long Story Short
description: Yet another unfinished roguelike game.

grade: devel
confinement: devmode

parts:
  conan:
    plugin: python
    python-version: python3
    python-packages:
      - conan
  lss:
    plugin: nil
    source-type: git
    source: https://github.com/averrin/lss.git
    after: [conan, desktop-gtk3]
    build-packages:
      - make
      - libsdl1.2-dev
      - libsdl-net1.2-dev
      - libsdl-sound1.2-dev
      - libasound2-dev
      - software-properties-common
      - wget
    override-build: |
      sudo add-apt-repository ppa:jonathonf/gcc-7.1
      sudo apt-get update
      sudo apt-get install -y gcc-7 g++-7
      export CXX=/usr/bin/g++-7
      export CC=/usr/bin/gcc-7
      wget https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.sh
      chmod +x cmake-3.12.1-Linux-x86_64.sh
      sudo  ./cmake-3.12.1-Linux-x86_64.sh --skip-license --prefix=/usr
      conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      conan install -s compiler.version=7.1 --build=missing .
      cmake .
      make -j4
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv bin/* $SNAPCRAFT_PART_INSTALL/bin

    filesets:
      wanted:
        - bin/*
    prime:
      - $wanted
  packages:
    plugin: nil
    after: [lss]
    stage-packages:
      - libstdc++6
      - libsdl2-2.0-0
      - libsdl2-gfx-1.0-0
      - libdrm2
      - libegl1-mesa
      - libglu1-mesa
      - libgles2-mesa
      - libgl1-mesa-dri

apps:
  lss:
    plugs: [opengl, desktop, desktop-legacy]
    command: desktop-launch $SNAP/bin/LSS
